# Generated by Django 5.1.2 on 2024-11-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='STKPushRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12)),
                ('amount', models.IntegerField()),
                ('trans_ref', models.CharField(blank=True, max_length=11, null=True)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('resp', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
